GET http://localhost:2020/posts
Content-Type: application/json
###


POST http://localhost:2020/posts
Content-Type: application/json

{
    "title": "Depression",
    "description": "Depression (major depressive disorder) is a common and serious medical illness that negatively affects how you feel, the way you think and how you act.",
    "catergory": "Depression",
    "img": "https://imgkub.com/images/2022/03/22/sadness-ge594f7b32_1920.jpg"
    
   
}

###

DELETE http://localhost:2020/posts


###

PATCH http://localhost:2020/posts
Comment-Type: application/json
{
    "description": "Blog"
}

###

//for users
GET http://localhost:2020/users

###

POST http://localhost:2020/users/register
Content-Type: application/json

{
    "name": "zharne",
    "password": "0123",
    "email": "zharnedesember@gmail.com"
}

###

POST http://localhost:2020/users/login
Content-Type: application/json

{
    "name": "zharne",
    "password": "0123"
}

###

POST http://localhost:2020/users/comments
Comment-Type: application/json
{
    "comment": ""
}

###

DELETE http://localhost:2020/users

###

PATCH http://localhost:2020/users
Comment-Type: application/json
{
    "description": "Blog"
}


 