GET http://localhost:5001/posts
Content-Type: application/json
###


POST http://localhost:5001/posts
Content-Type: application/json

{
    "title": "zharne",
    "description":"zharnedesember@gmail.com",
    "catergory":"user",
    "created_by": "",
    "date": "",
    "comments": "okay, and what?"
}

###

DELETE http://localhost:5001/posts


###

PATCH http://localhost:5001/posts
Comment-Type: application/json
{
    "description": "Blog"
}

###

//for users
GET http://localhost:5001/users

###

POST http://localhost:5001/users/signup
Content-Type: application/json

{
    "name": "zharne",
    "password": "0123",
    "email": "zharnedesember@gmail.com",

}

###

POST http://localhost:5001/users/login
Content-Type: application/json

{
    "name": "",
    "password": ""
}

###

POST http://localhost:5001/users/comments
Comment-Type: application/json
{
    "comment": ""
}

###

DELETE http://localhost:5001/users

###

PATCH http://localhost:5001/users
Comment-Type: application/json
{
    "description": "Blog"
}


 