GET 
Content-Type: application/json
###


POST https://mental-health-association.herokuapp.com/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDgyMTA5MDEsImV4cCI6MTY0ODI5NzMwMX0.S8vkSNvZ1N11cJXxfSTfWT2guDMr5npavaZedLurWCg

   { 
    "title": "Mental Health",
    "description": "“Mental health is a state of well-being in which an individual realizes his or her own abilities, can cope with the normal stresses of life, can work productively, and is able to make a contribution to his or her community.”",
    "catergory": "",
    "img": "https://imgkub.com/images/2022/03/22/mental-health-gf3b036b3e_1920.jpg"
     
    }

###

DELETE http://localhost:2020/posts


###

PATCH http://localhost:2020/posts
Comment-Type: application/json
{
    "description": "Blog"
}

###

//for users
GET http://localhost:2020/users

###

POST http://localhost:2020/users/register
Content-Type: application/json

{
    "username": "tony1",
    "password": "1234abcd",
    "email": "tony@gmail.com"
}

###

POST https://mental-health-association.herokuapp.com/users/register
Content-Type: application/json

{
    "name": "tony",
    "password": "1234abcd"
}

###

POST https://mental-health-association.herokuapp.com/contact
Comment-Type: application/json
{
    "name": "This is a comment",
    "email":"zharnedesember@gmail.com",
    "message":"message"
}

###

DELETE http://localhost:2020/users

###

PATCH http://localhost:2020/users
Comment-Type: application/json
{
    "description": "Blog"
}


 